### ISSUE TITLE
Unable to install packages on Hyper-V Vm's

### ISSUE THREAD

**Issue by Shilpaklala** [chocolatey/boxstarter#252]
```
Import-Module Boxstarter.HyperV
$cred=Get-Credential ******** 
"test_box" |Enable-BoxstarterVM -Credential $cred | Install-BoxstarterPackage -PackageName "******" 
```

this throws an error as below

```
[WIN-QN7UOPUJ8J2]Boxstarter: Disabling Automatic Updates from Windows Update
[WIN-QN7UOPUJ8J2]+ Boxstarter starting Calling Chocolatey to install box_package_shilpa. This may take several minutes to complete...
[WIN-QN7UOPUJ8J2]Boxstarter: Error from chocolatey: 

ErrorRecord                 : Cannot convert value "System.Object[]" to type "System.Xml.XmlDocument". Error: "Root element is missin
                              g."
StackTrace                  :    at System.Management.Automation.ArgumentTypeConverterAttribute.Transform(EngineIntrinsics engineIntr
                              insics, Object inputData, Boolean bindingParameters, Boolean bindingScriptCmdlet)
                                 at System.Management.Automation.ArgumentTypeConverterAttribute.Transform(EngineIntrinsics engineIntr
                              insics, Object inputData)
                                 at System.Management.Automation.VariableDereferenceNode.UpdateVariable(PSVariable variable, Object v
                              alue)
                                 at System.Management.Automation.VariableDereferenceNode.PrivateSetValue(Object value, ExecutionConte
                              xt context)
                                 at System.Management.Automation.VariableDereferenceNode.SetValue(Object value, ExecutionContext cont
                              ext)
                                 at System.Management.Automation.AssignmentStatementNode.Execute(Array input, Pipe outputPipe, Execut
                              ionContext context)
                                 at System.Management.Automation.StatementListNode.ExecuteStatement(ParseTreeNode statement, Array in
                              put, Pipe outputPipe, ArrayList& resultList, ExecutionContext context)
WasThrownFromThrowStatement : False
Message                     : Cannot convert value "System.Object[]" to type "System.Xml.XmlDocument". Error: "Root element is missin
                              g."
Data                        : {}
InnerException              : System.Management.Automation.PSInvalidCastException: Cannot convert value "System.Object[]" to type "Sy
                              stem.Xml.XmlDocument". Error: "Root element is missing." ---> System.Xml.XmlException: Root element is 
                              missing.
                                 at System.Xml.XmlTextReaderImpl.Throw(Exception e)
                                 at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
                                 at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
                                 at System.Xml.XmlDocument.Load(XmlReader reader)
                                 at System.Xml.XmlDocument.LoadXml(String xml)
                                 at System.Management.Automation.LanguagePrimitives.ConvertToXml(Object valueToConvert, Type resultTy
                              pe, Boolean recursion, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backu
                              pTable)
                                 --- End of inner exception stack trace ---
                                 at System.Management.Automation.LanguagePrimitives.ConvertToXml(Object valueToConvert, Type resultTy
                              pe, Boolean recursion, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backu
                              pTable)
                                 at System.Management.Automation.LanguagePrimitives.ConvertTo(Object valueToConvert, Type resultType,
                               Boolean recursion, IFormatProvider formatProvider, TypeTable backupTypeTable)
                                 at System.Management.Automation.ArgumentTypeConverterAttribute.Transform(EngineIntrinsics engineIntr
                              insics, Object inputData, Boolean bindingParameters, Boolean bindingScriptCmdlet)
TargetSite                  : Void ExecuteStatement(System.Management.Automation.ParseTreeNode, System.Array, System.Management.Autom
                              ation.Internal.Pipe, System.Collections.ArrayList ByRef, System.Management.Automation.ExecutionContext)
HelpLink                    : 
Source                      : System.Management.Automation




[WIN-QN7UOPUJ8J2]+ Boxstarter finished Calling Chocolatey to install box_package_shilpa. This may take several minutes to complete... 
00:00:04.0691056
[WIN-QN7UOPUJ8J2]Boxstarter: Restore Automatic Updates from Windows Update


Errors       : {Cannot convert value "System.Object[]" to type "System.Xml.XmlDocument". Error: "Root element is missing."}
ComputerName : win-qn7uopuj8j2
Completed    : True
FinishTime   : 4/25/2017 1:49:56 AM
StartTime    : 4/25/2017 1:49:11 AM

Boxstarter: Rolling back remoting settings changed by Boxstarter...
``

**Comment by mwrock** [comment]
Does it work on non Hyper-V systems and do you get this same error regardless of the package or only this package?

**Comment by Shilpaklala** [comment]
regardless of the package I get this error

**Comment by Shilpaklala** [comment]
Can you please help on this at the earliest

**Comment by mwrock** [comment]
I'm having trouble reproducing this. Here is a log of a install I am trying:

I'm curious if a public package like windirstat which I'm installing below fails for you. do the packages install succesfully if you try to install them locally instead of remotely? A gist of the boxstarter log file would also be helpful. The log is located at `$env:localappdata\boxstarter\boxstarter.log`.
```
[WIN-PQGGDBC3BHO]Boxstarter: Installing package windirstat
[WIN-PQGGDBC3BHO]Boxstarter: Disabling Automatic Updates from Windows Update
[WIN-PQGGDBC3BHO]++ Boxstarter starting Calling Chocolatey to install windirstat. This may take several minutes to complete...
Installing the following packages:
windirstat
By installing you accept licenses for the packages.

windirstat v1.1.2.20161210 (forced)
 [WIN-PQGGDBC3BHO]Boxstarter: Expanded splat to -silentArgs "/S" -file "C:\ProgramData\chocolatey\lib\windirstat\tools\windirstat1_1_2_setup.exe" -packageName "WinDirStat" -validExitCodes @(0) -fileType "exe"
 Installing WinDirStat...
 WinDirStat has been installed.
 The install of windirstat was successful.

Chocolatey installed 1/1 package(s). 0 package(s) failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
[WIN-PQGGDBC3BHO]++ Boxstarter finished Calling Chocolatey to install windirstat. This may take several minutes to complete... 00:00:30.5943167
[WIN-PQGGDBC3BHO]Boxstarter: Restore Automatic Updates from Windows Update


Errors       : {}
ComputerName : 192.168.137.52
Completed    : True
FinishTime   : 4/28/2017 11:42:56 PM
StartTime    : 4/28/2017 11:41:22 PM
```

**Comment by pauby** [comment]
@Shilpaklala I appreciate this was some time ago but did you resolve this or is it still an issue?

**Comment by pauby** [comment]
There has been no updates to this in some time, so I'm going to go ahead and close it. We can always reopen it again if needed.
