### ISSUE TITLE
2.11.0 packages missing chocolatey dlls for remote installs

### ISSUE THREAD

**Issue by mdonoughe** [chocolatey/boxstarter#324]
Trying to do remote installs is failing because the boxstarter.zip copied to the remote machine is missing the Boxstarter.Chocolatey/chocolatey folder and therefore the Chocolatey dll files are missing from the remote machine.

**Comment by gep13** [comment]
@mdonoughe thank you for making this report.  Can you please provide some additional information so that we can begin troubleshooting this?

i.e. can you provide a complete set of steps to reproduce the problem that you are facing?

**Comment by flcdrg** [comment]
Matthew, can you include the exact commands that you used?

Thanks,
David

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mdonoughe** [comment]
```ps1
Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
choco install boxstarter
New-BoxstarterPackage -Name test-package
Invoke-BoxStarterBuild -Name test-package
Install-BoxstarterPackage -ComputerName test-subject -Credential (Get-Credential) test-package
```

```
cmdlet Get-Credential at command pipeline position 1
Supply values for the following parameters:
Credential
Boxstarter Version 2.11.0
(c) 2018 Chocolatey Software, Inc, 2012 - 2018 Matt Wrock. https://boxstarter.org

Boxstarter: Configuring local PowerShell Remoting settings...
Boxstarter: Configuring CredSSP settings...
Boxstarter: Testing remoting access on test-subject...
Boxstarter: Remoting is accessible on test-subject
Boxstarter: Copying Boxstarter Modules and LocalRepo packages at C:\ProgramData\Boxstarter to C:\Users\mdono\AppData\Local\Temp\chocolatey on test-subject...
Boxstarter: Creating a scheduled task to enable CredSSP Authentication on test-subject...
Boxstarter: CredSSP session succeeded. Replacing sessions...
Boxstarter: Running remote install...
[test-subject]Boxstarter: Installing package test-package
[test-subject]Boxstarter: Disabling Automatic Updates from Windows Update
[test-subject]Boxstarter: Restore Automatic Updates from Windows Update
[test-subject]Boxstarter: Restart Required. Restarting now...
Boxstarter: Waiting for test-subject to sever remote session...
Boxstarter: Waiting for test-subject to respond to remoting...
Boxstarter: Running remote install...
[test-subject]Boxstarter: Installing package test-package
[test-subject]Boxstarter: Disabling Automatic Updates from Windows Update
[test-subject]++ Boxstarter starting Calling Chocolatey to install test-package. This may take several minutes to complete...
[test-subject]Boxstarter: Error from Chocolatey:

Message                     : Cannot bind parameter 'Path' to the target. Exception setting "Path": "Cannot find path '
                              C:\Users\mdono\AppData\Local\Temp\Boxstarter\boxstarter.chocolatey\chocolatey\log4net.dll
                              ' because it does not exist."
ParameterName               : Path
ParameterType               : System.String[]
TypeSpecified               : System.String[]
ErrorId                     : ParameterBindingFailed
Line                        : 15
Offset                      : 28
CommandInvocation           : System.Management.Automation.InvocationInfo
ErrorRecord                 : Cannot bind parameter 'Path' to the target. Exception setting "Path": "Cannot find path '
                              C:\Users\mdono\AppData\Local\Temp\Boxstarter\boxstarter.chocolatey\chocolatey\log4net.dll
                              ' because it does not exist."
WasThrownFromThrowStatement : False
Data                        : {System.Management.Automation.Interpreter.InterpretedFrameInfo}
InnerException              : System.Management.Automation.SetValueInvocationException: Exception setting "Path":
                              "Cannot find path 'C:\Users\mdono\AppData\Local\Temp\Boxstarter\boxstarter.chocolatey\cho
                              colatey\log4net.dll' because it does not exist." --->
                              System.Management.Automation.ItemNotFoundException: Cannot find path 'C:\Users\mdono\AppD
                              ata\Local\Temp\Boxstarter\boxstarter.chocolatey\chocolatey\log4net.dll' because it does
                              not exist.
                                 at System.Management.Automation.LocationGlobber.ExpandMshGlobPath(String path,
                              Boolean allowNonexistingPaths, PSDriveInfo drive, ContainerCmdletProvider provider,
                              CmdletProviderContext context)
                                 at System.Management.Automation.LocationGlobber.ResolveDriveQualifiedPath(String
                              path, CmdletProviderContext context, Boolean allowNonexistingPaths, CmdletProvider&
                              providerInstance)
                                 at
                              System.Management.Automation.LocationGlobber.GetGlobbedMonadPathsFromMonadPath(String
                              path, Boolean allowNonexistingPaths, CmdletProviderContext context, CmdletProvider&
                              providerInstance)
                                 at
                              System.Management.Automation.LocationGlobber.GetGlobbedProviderPathsFromMonadPath(String
                              path, Boolean allowNonexistingPaths, CmdletProviderContext context, ProviderInfo&
                              provider, CmdletProvider& providerInstance)
                                 at
                              System.Management.Automation.LocationGlobber.GetGlobbedProviderPathsFromMonadPath(String
                              path, Boolean allowNonexistingPaths, ProviderInfo& provider, CmdletProvider&
                              providerInstance)
                                 at Microsoft.PowerShell.Commands.AddTypeCommandBase.set_Path(String[] value)
                                 at System.Management.Automation.ReflectionParameterBinder.BindParameter(String name,
                              Object value, CompiledCommandParameter parameterMetadata)
                                 --- End of inner exception stack trace ---
                                 at System.Management.Automation.ReflectionParameterBinder.BindParameter(String name,
                              Object value, CompiledCommandParameter parameterMetadata)
                                 at
                              System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal
                              parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
TargetSite                  : Void CheckActionPreference(System.Management.Automation.Language.FunctionContext,
                              System.Exception)
StackTrace                  :    at
                              System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext
                              funcContext, Exception exception)
                                 at
                              System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame
                              frame)
                                 at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(Interp
                              retedFrame frame)
                                 at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(Interp
                              retedFrame frame)
                                 at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                                 at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                                 at
                              System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInvoke
                              clauseToInvoke, Boolean createLocalScope, Dictionary`2 functionsToDefine, List`1
                              variablesToDefine, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder,
                              Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo,
                              Object[] args)
                                 at
                              System.Management.Automation.ScriptBlock.<>c__DisplayClass57_0.<InvokeWithPipe>b__0()
                                 at System.Management.Automation.Runspaces.RunspaceBase.RunActionIfNoRunningPipelinesWi
                              thThreadCheck(Action action)
                                 at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope,
                              ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object
                              scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Boolean
                              propagateAllExceptionsToTop, List`1 variablesToDefine, Dictionary`2 functionsToDefine,
                              Object[] args)
                                 at System.Management.Automation.ScriptBlock.InvokeUsingCmdlet(Cmdlet contextCmdlet,
                              Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder,
                              Object input, Object scriptThis, Object[] args)
                                 at Microsoft.PowerShell.Commands.ForEachObjectCommand.ProcessRecord()
                                 at System.Management.Automation.CommandProcessor.ProcessRecord()
HelpLink                    :
Source                      : System.Management.Automation
HResult                     : -2146233087




[test-subject]++ Boxstarter finished Calling Chocolatey to install test-package. This may take several minutes to complete... 00:00:00.6330805
[test-subject]Boxstarter: Restore Automatic Updates from Windows Update


Errors       : {$null, Cannot bind parameter 'Path' to the target. Exception setting "Path": "Cannot find path
               'C:\Users\mdono\AppData\Local\Temp\Boxstarter\boxstarter.chocolatey\chocolatey\log4net.dll' because it
               does not exist."}
ComputerName : test-subject
Completed    : True
FinishTime   : 7/28/2018 2:38:51 PM
StartTime    : 7/28/2018 2:35:07 PM

Boxstarter: Rolling back remoting settings changed by Boxstarter...
```

zip on host machine with no chocolatey folder:
![mstsc_2018-07-28_10-29-41](https://user-images.githubusercontent.com/17961/43357698-b8a31e88-9253-11e8-8500-6a7797c41b3c.png)

directory on target machine with no chocolatey folder:
![mstsc_2018-07-28_10-44-03](https://user-images.githubusercontent.com/17961/43357710-d3ee2bba-9253-11e8-9423-c5c31e4f8d12.png)
